### ISSUE TITLE
N-Acetylglucosamin (C8H15NO6) = NAG

### ISSUE THREAD

**Issue by ihamidindar** [lvpp/sigma#10]
For the reaction:
NAG + H3O+ <-> H2O + NAGH+ 
I need the LVPP sigma-profile database for COSMO-based models for two new components N-Acetylglucosamin and its hydrated ion NAGH+

NAGH+ = C8H16NO6+

[NAG.txt](https://github.com/lvpp/sigma/files/3525161/NAG.txt)
[NAGH+.txt](https://github.com/lvpp/sigma/files/3525162/NAGH%2B.txt)

**Comment by rpseng** [comment]
Please find attached the requested sigma-profiles.

This issue will be left open until these files are included in a release.

[NAGs.zip](https://github.com/lvpp/sigma/files/3534364/NAGs.zip)

**Comment by ihamidindar** [comment]
Thank you very much for your help.
Is the output file of N-ACETYLGLUCOSAMINE +1 ion certainly correct? The term  (e / A ** 2) have some very large values, even bigger than 0.04!
therefore, in contrast to N-ACETYLGLUCOSAMINE, no sigma profile can be produced from it.

**Comment by rpseng** [comment]
I have not checked the resulting files, we will take a look. Anyway, for ions we can have larger charge densities values. Our COSMO-SAC codes are not limited to values smaller than 0.025.

**Comment by ihamidindar** [comment]
Thanks. Is your COSMO-SAC codes the F-SAC model?
can one use that too?

**Comment by rpseng** [comment]
No, the difference between F-SAC and COSMO-SAC is that the first do not require a sigma profile computed by GAMESS or other quantum chemistry package. For F-SAC the sigma profile is given by a set of parameters to be fitted with experimental data for each functional group.

There is a demonstration code for F-SAC here: https://github.com/lvpp/f-sac

**Comment by rpseng** [comment]
These mol files were added on #18, they will be available on the next release.
