### ISSUE TITLE
Mint doi for release?

### ISSUE THREAD

**Issue by ianhbell** [lvpp/sigma#11]
I would like to cite your repository in our upcoming paper, but the best way to do that is to have an archival release version with a DOI.  Could you please mint a DOI for your release version so I can make direct reference to that particular release?  Systems like zenodo make this process seamless.

**Comment by rpseng** [comment]
Thanks for the upcoming citation and for the tip on zenodo! The only problem, apparently it is not possible to import an existing release on it, as per https://github.com/zenodo/zenodo/issues/1463

I'll see if there is any other workaround, otherwise we can try to make a new release for this.

**Comment by ianhbell** [comment]
Yeah, I had the same experience.  A "bugfix" release with a DOI is an option, or I can also use an existing release, but the DOI approach is superior in terms of cross-referencing, citation counting on google scholar, etc.

**Comment by rpseng** [comment]
Thanks again for the tip, it is now available at https://doi.org/10.5281/zenodo.3613786

**Comment by ianhbell** [comment]
Thank you very much, citation on its way :)
