### ISSUE TITLE
Carotenoids

### ISSUE THREAD

**Issue by allanmorcelli** [lvpp/sigma#12]
Hello, I would like to request the inclusion of some key carotenoids found in microalgae in LVPP's sigma-profile database for COSMO-based models. 

all-trans-betacarotene
all-trans-lutein
all-trans-zeaxanthin
all-trans-violaxanthin

[carotenoids.zip](https://github.com/lvpp/sigma/files/4123306/carotenoids.zip)

Files containing molecules with minimum energy structures are attached. 

Best regards,

Allan Morcelli

**Comment by rpseng** [comment]
Fixed by PR #17
