### ISSUE TITLE
NA+1 not supported

### ISSUE THREAD

**Issue by gsimon-ens** [lvpp/sigma#14]
Hello,
NA+1 present in the library is not supported by jcosmo, it displays the message 'Compound not found'. The problem is the same for a new gout file obtained with GAMESS. 

Is it a normal issue?
Please find attached the gout files in .txt format.
[NA+1_library.txt](https://github.com/lvpp/sigma/files/4204071/NA%2B1_library.txt)
[NA+1_new.txt](https://github.com/lvpp/sigma/files/4204090/NA%2B1_new.txt)

Best,
Guillaume Simon

**Comment by rpseng** [comment]
Dear @gsimon-ens,

Indeed we are having some issues with GAMESS output files that come out slightly different. For instance for your *new* file, apparently the geometry optimization is off, so the output file is different. We are working on it.

**Comment by gsimon-ens** [comment]
Dear @rpseng ,

Thank you, is it the same output file issue with the NA+1 file coming from the JCOSMO library?

Best,
Guillaume Simon

**Comment by rpseng** [comment]
Hello,

Gamess output files were reworked and are now much smaller, we also took the opportunity to fix this problem. The latest release and JCOSMO now include NA+ and many other molecules/ions.
