### ISSUE TITLE
scons [tab error] inconsisten used of tab or indentation

### ISSUE THREAD

**Issue by Anggawirya** [lvpp/sigma#46]
Hello,

Im having a error message when running scons, it states that "
scons: Reading SConscript files ...
  File "/home/anggawirya/sigma-master/GAMESS/SConstruct", line 102

    print(len(gamess_version))

                              ^

TabError: inconsistent use of tabs and spaces in indentation

do you know what might wrong in my case ? Many thanks

**Comment by rpseng** [comment]
Hello, this should be fixed now.
