### ISSUE TITLE
1,1,2-TRICHLOROETHANE conformers

### ISSUE THREAD

**Issue by rpseng** [lvpp/sigma#5]
Please check if the 1,1,2-TRICHLOROETHANE conformation should be as here: https://webbook.nist.gov/cgi/cbook.cgi?Str3View=C79005&Type=JSmol

**Comment by fferrarini** [comment]
This possible conformation for 1,1,2-trichloroethane presents a slightly higher energy when it is compared to this one: 
https://pubchem.ncbi.nlm.nih.gov/compound/1_1_2-trichloroethane#section=3D-Conformer&fullscreen=true
The last one is present on our database (HF+TZVP).
