### ISSUE TITLE
Cyclopentyl methyl ether

### ISSUE THREAD

**Issue by henriquegasparetto** [lvpp/sigma#52]
Olá Rafael! Você poderia incluir a molécula Cyclopentyl methyl ether (CAS 5614-37-9, SMILE COC1CCCC1) no JCOSMO? Tenho usado suas referências em meus trabalhos de extração de óleo de soja utilizando solventes verdes:

https://doi.org/10.1016/j.jiec.2022.06.020

Atenciosamente! Abraço!

**Comment by hiquegtt** [comment]
Segue o arquivo .mol

**Comment by rpseng** [comment]
The mol file was included and it will be available in the next release.
