### ISSUE TITLE
Cinnamic acid derivatives (CADs)

### ISSUE THREAD

**Issue by rpseng** [lvpp/sigma#8]
Please add the following CADs:
- p-coumaric acid
- caffeic acid
- methyl p-coumarate
- methyl ferulate
- methyl sinapate

**Comment by rpseng** [comment]
Structures of these molecules can be found here: dx.doi.org/10.1016/j.fluid.2014.02.015

**Comment by fferrarini** [comment]
These compounds were computed and will be added in the next release.
