### ISSUE TITLE
Scons Error 1 - Illegal Variable name

### ISSUE THREAD

**Issue by RhayWenn** [lvpp/sigma#89]
Hello! Could you help me?

Scons is returning error 1 when trying to generate the sigma profile. 
I've tried to compute sigma-p for LACTIC_ACID.mol, using the mol file provided in the database.

It seems it computes the calculation up to the line:

/home/csrafaelcs/src/gamess/rungms LACTIC_ACID.inp > LACTIC_ACID.gamout

After this, I get an error: Illegal variable name.

And it ends with a error 1 from scons.

Complete terminal lines are:

scons: Reading SConscript files ...
LACTIC_ACID.gout
Delete([])
scons: done reading SConscript files.
scons: Building targets ...
/home/csrafaelcs/src/gamess/rungms LACTIC_ACID.inp > LACTIC_ACID.gamout
Illegal variable name.
scons: *** [LACTIC_ACID.gamout] Error 1
scons: building terminated because of errors.

Any solution?

**Comment by RhayWenn** [comment]
I've reinstalled gamess using the version pointed out in the tutorial (gamess.Apr202017R1, i think), and it worked well in my Ubuntu 24.0.

It generated the .gout file for Lactic Acid molecule that has a sigma-profile quite similar to the that one in Jcosmo database.

**Comment by rpseng** [comment]
Hello, glad to know you got it working.

Since the issue was apparently related to gamess, I'm closing this for now.
