### ISSUE TITLE
GAMESS for generation of Sigma profiles - too slow

### ISSUE THREAD

**Issue by RhayWenn** [lvpp/sigma#90]
Hello! I'm a newbie in COSMO calculations and I am trying to compute the sigma profiles using GAMESS by my own.

I've followed the tutorial and I have achieved to generate the .gout file for simple molecules like Lactic acid using GAMESS.

Then, I've tried to generate the .gout file for my molecule, praziquantel (). It worked very well but it demanded more than 10 hours to finish the calculations!

I would like to know if the calculations take this huge time to conclude normally? 

I would be quite grateful if anyone could give me some tips to accelerate the calculations. 

I tried to increase the memory changing the "kernel.shmmax" to 8000000000 and changing the MSWORDS (base.keys.gamess file) to 2000. But it takes more than 10 hours yet. 

JCOSMO read my .gout file so I am considering that everything worked well. I appended the files if you want to check it.

Thanks.
[S-PRAZIQUANTEL.zip](https://github.com/lvpp/sigma/files/15324918/S-PRAZIQUANTEL.zip)

**Comment by rpseng** [comment]
Hello, yes, depending on your machine and molecule size, it can take many days to finish.
